### ISSUE TITLE
001 : 클린 아키텍처 개념 공부 ( ~ 05/03 )

### ISSUE THREAD

**Issue by hoyahozz** [hoyahozz/Clean-Architecture-Study#1]
## 클린 아키텍처 개념 공부

- [x] 블로그, 유튜브등을 이용하여 개념 공부하기
- [x] YAPP 19기 **딜리버디** 코드 참고해서 개념 공부하기
- [x] **구글 블루프린트** 코드 참고해서 개념 공부하기
- [x] 시간 남으면 개념 공부 후 블로그에 포스팅

**Comment by jihee-dev** [comment]
와 머야,, 왜 저희 프로젝트 보고 공부하셨어요 ㅋㅋㅋㅋ큐ㅠㅠ 부끄럽당
