### ISSUE TITLE
Hilt 개념에 관하여

### ISSUE THREAD

**Issue by KwonDae** [hoyahozz/Clean-Architecture-Study#4]
무작정 사람들이 Hilt 를 도입하니까 나도 해야지!
가 아니라
필요성을 알고 그 배경에 무엇이 있는지,
DI를 사용하지 않던 이전 프로젝트에서 어떤 번거로움과 이슈가 있었는지 생각을 해보고
공부해봅시다!

**Comment by hoyahozz** [comment]
**필요성과 그 전 과정에서 있던 이슈**
뿌리부터 찬찬히 살펴보겠습니닷..
