### ISSUE TITLE
깃헙 약어

### ISSUE THREAD

**Issue by KwonDae** [hoyahozz/Clean-Architecture-Study#7]
**이슈 내용**
- 깃헙에서 약어를 많이 사용하는거 같은데 앞으로 우리 리뷰할떄도 쓰면 편할듯합니당

https://hidekuma.github.io/github/abbreviation/abbreviation/

**Comment by hoyahozz** [comment]
저도 이거 받아보고 싶어요..ㅋㅋㅋㅋ
> LGTM 👍

**Comment by KwonDae** [comment]
LGTM 👍
